// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentCycleWebApp.Models
{
    public partial class DeviceModel
    {
        public DeviceModel()
        {
            DeviceRates = new HashSet<DeviceRate>();
            DeviceShadows = new HashSet<DeviceShadow>();
        }

        public int Id { get; set; }
        public string DeviceModel1 { get; set; }

        public virtual ICollection<DeviceRate> DeviceRates { get; set; }
        public virtual ICollection<DeviceShadow> DeviceShadows { get; set; }
    }
}