// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentCycleWebApp.Models
{
    public partial class DeviceRate
    {
        public DeviceRate()
        {
            UserRideCosts = new HashSet<UserRideCost>();
        }

        public int Id { get; set; }
        public int DeviceModelId { get; set; }
        public int UserCategoryId { get; set; }
        public decimal Rate { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public DateTime? EffectiveStartDate { get; set; }
        public DateTime? EffectiveEndDate { get; set; }

        public virtual DeviceModel DeviceModel { get; set; }
        public virtual UserCategory UserCategory { get; set; }
        public virtual ICollection<UserRideCost> UserRideCosts { get; set; }
    }
}