// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentCycleWebApp.Models
{
    public partial class PaymentMode
    {
        public PaymentMode()
        {
            UserPayments = new HashSet<UserPayment>();
        }

        public int Id { get; set; }
        public string PaymentMode1 { get; set; }

        public virtual ICollection<UserPayment> UserPayments { get; set; }
    }
}