// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentCycleWebApp.Models
{
    public partial class UserAccount
    {
        public UserAccount()
        {
            UserAccountBalances = new HashSet<UserAccountBalance>();
            UserPayments = new HashSet<UserPayment>();
            UserRideInfos = new HashSet<UserRideInfo>();
        }

        public int Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UsercategoryId { get; set; }

        public virtual ICollection<UserAccountBalance> UserAccountBalances { get; set; }
        public virtual ICollection<UserPayment> UserPayments { get; set; }
        public virtual ICollection<UserRideInfo> UserRideInfos { get; set; }
    }
}