// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentCycleWebApp.Models
{
    public partial class UserRideInfo
    {
        public UserRideInfo()
        {
            UserRideCosts = new HashSet<UserRideCost>();
        }

        public int Id { get; set; }
        public int UserAccountId { get; set; }
        public string DeviceId { get; set; }
        public DateTime? ScanStartTime { get; set; }
        public DateTime? ScanEndTime { get; set; }
        public DateTime? UnlockTime { get; set; }
        public DateTime? LockTime { get; set; }
        public string StartPosition { get; set; }
        public string EndPosition { get; set; }

        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<UserRideCost> UserRideCosts { get; set; }
    }
}