// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentCycleWebApp.Models
{
    public partial class UserPayment
    {
        public int Id { get; set; }
        public int UserAccountId { get; set; }
        public decimal Amount { get; set; }
        public int PaymentModeId { get; set; }
        public DateTime PaymentDate { get; set; }
        public string TransactionId { get; set; }
        public bool? TransactionStatus { get; set; }

        public virtual PaymentMode PaymentMode { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}