// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentCycleWebApp.Models
{
    public partial class UserRideCost
    {
        public int Id { get; set; }
        public int UserRideInfoId { get; set; }
        public int DeviceRateId { get; set; }
        public decimal Cost { get; set; }

        public virtual DeviceRate DeviceRate { get; set; }
        public virtual UserRideInfo UserRideInfo { get; set; }
    }
}